name: Pipeline

on: push

jobs:
  app-sonarcloud:
    name: App sonarcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=sergio-forero
          -Dsonar.projectKey=tdd-api-suma-resta
          -Dsonar.sources=.
          -Dsonar.test.exclusions=SerenityCalculadoraTddNodeJs
    
  app-run:
    name: App run
    needs: app-sonarcloud
    runs-on: ubuntu-latest
    env:
      NODE-VERSION: 14.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: App build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE-VERSION }}
      - name: App test
        run: npm install & npm test
